/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemapedidos.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.ufpr.sistemapedidos.Cliente;
import org.ufpr.sistemapedidos.ClienteDao;
import org.ufpr.sistemapedidos.Cpf;
import org.ufpr.sistemapedidos.ItemDoPedido;
import org.ufpr.sistemapedidos.Pedido;
import org.ufpr.sistemapedidos.PedidoDao;
import org.ufpr.sistemapedidos.Produto;
import org.ufpr.sistemapedidos.ProdutoDao;

/**
 *
 * @author lb
 */
public class IncluirPedido extends javax.swing.JFrame {
    
    private modeloTabelaProdutos modeloTabela;
    private int linhaClicada = -1;
    private Pedido pedido;
    private List<ItemDoPedido> lista = new ArrayList();
    
    public IncluirPedido() {
        modeloTabela = new modeloTabelaProdutos();
        pedido = new Pedido();
        
        
        initComponents();
        this.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Busca = new javax.swing.JTextField();
        bu_Busca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        spinnerQtde = new javax.swing.JSpinner();
        bu_Adicionar = new javax.swing.JButton();
        tf_Cpf = new javax.swing.JTextField();
        bu_incluirPedido = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();
        buVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bu_Busca.setText("Buscar");
        bu_Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_BuscaActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(modeloTabela);
        jScrollPane1.setViewportView(tabelaProdutos);

        spinnerQtde.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));

        bu_Adicionar.setText("Adicionar");
        bu_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_AdicionarActionPerformed(evt);
            }
        });

        tf_Cpf.setText("CPF do cliente");

        bu_incluirPedido.setText("Fechar pedido");
        bu_incluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_incluirPedidoActionPerformed(evt);
            }
        });

        buVoltar.setText("Voltar");
        buVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Busca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spinnerQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_Adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_incluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_Busca)
                    .addComponent(buVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_Adicionar)
                    .addComponent(tf_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_incluirPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bu_BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_BuscaActionPerformed
        try {
            String termo = tf_Busca.getText();
            if(termo.equals("")){
                this.atualizaTabela();
            }
            else{
                ProdutoDao dao = new ProdutoDao();
                List<Produto> lista = dao.buscarProdutos(termo);
                modeloTabela.setLista(lista);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bu_BuscaActionPerformed

    private void bu_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_AdicionarActionPerformed
        linhaClicada = tabelaProdutos.getSelectedRow();
        
        if(linhaClicada != -1)
        {
            Produto prod = modeloTabela.getProduto(linhaClicada);
            try {
                spinnerQtde.commitEdit();
            } catch ( java.text.ParseException e ){
                JOptionPane.showMessageDialog(new JFrame(), "Quantidade inválida", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            int qtde = (Integer) spinnerQtde.getValue();
            
            ItemDoPedido item = new ItemDoPedido(qtde, prod);
            lista.add(item);
            this.atualizaTabela();
            labelMensagem.setText("(" + qtde + ") " + prod.getDescricao() + " adicionado ao pedido.");
        }
        else
        {
            JOptionPane.showMessageDialog(new JFrame(), "Selecione um produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bu_AdicionarActionPerformed

    private void bu_incluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_incluirPedidoActionPerformed
        
        ClienteDao clienteDao = new ClienteDao();
        PedidoDao pedidoDao = new PedidoDao();
        try {
            Cpf cpf = new Cpf(tf_Cpf.getText());
            Cliente cliente = clienteDao.consultarCpf(cpf.toString());
            
            pedido.setCliente(cliente);
            pedido.setItens(lista);

            pedidoDao.incluirPedido(pedido);
            labelMensagem.setText("Pedido adicionado em " + pedido.getData().toString());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), "CPF não cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bu_incluirPedidoActionPerformed

    private void buVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buVoltarActionPerformed
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_buVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncluirPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buVoltar;
    private javax.swing.JButton bu_Adicionar;
    private javax.swing.JButton bu_Busca;
    private javax.swing.JButton bu_incluirPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JSpinner spinnerQtde;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField tf_Busca;
    private javax.swing.JTextField tf_Cpf;
    // End of variables declaration//GEN-END:variables

    private void atualizaTabela() {
        try {
            ProdutoDao dao = new ProdutoDao();
            List<Produto> lista = dao.listarProdutos();
            this.linhaClicada = -1;
            modeloTabela.setLista(lista);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro ao atualizar tabela.", JOptionPane.ERROR_MESSAGE);
        }
    }
}
