package org.ufpr.sistemapedidos.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.ufpr.sistemapedidos.Cliente;
import org.ufpr.sistemapedidos.ClienteDao;
import org.ufpr.sistemapedidos.Cpf;
import org.ufpr.sistemapedidos.ItemDoPedido;
import org.ufpr.sistemapedidos.Pedido;
import org.ufpr.sistemapedidos.PedidoDao;

public class ListarPedido extends javax.swing.JFrame {
    
    private modeloTabelaPedido modeloTabela;
    private Pedido pedido;
    private List<ItemDoPedido> listaItens = new ArrayList();
    private List<Pedido> listaPedidos = new ArrayList();
    
    public ListarPedido() {
        
        modeloTabela = new modeloTabelaPedido();
        pedido = new Pedido();
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCpf = new javax.swing.JTextField();
        buBuscar = new javax.swing.JButton();
        cbPedidoId = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();
        buVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tfCpf.setText("CPF");

        buBuscar.setText("Buscar");
        buBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buBuscarActionPerformed(evt);
            }
        });

        cbPedidoId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPedidoIdItemStateChanged(evt);
            }
        });

        tabelaPedido.setModel(modeloTabela);
        jScrollPane1.setViewportView(tabelaPedido);

        buVoltar.setText("Voltar");
        buVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPedidoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buBuscar)
                    .addComponent(cbPedidoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buBuscarActionPerformed

        try {
            if(!tfCpf.getText().equals(""))
            {
                cbPedidoId.removeAllItems();
                modeloTabela.limpaTabela();
                Cpf cpf = new Cpf(tfCpf.getText());
                String cpfString = cpf.toString();
                ClienteDao clienteDao = new ClienteDao();
                Cliente cliente = clienteDao.consultarCpf(cpfString);
                PedidoDao pedidoDao = new PedidoDao();
                
                this.listaPedidos = pedidoDao.listarPedidosDeCliente(cliente);

                for(Pedido ped : listaPedidos)
                {
                    cbPedidoId.addItem(ped.getId()+"");
                }
                
            }
            else
            {
                modeloTabela.limpaTabela();
            }

            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_buBuscarActionPerformed

    private void cbPedidoIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPedidoIdItemStateChanged
        
        
//        System.out.println(cbPedidoId.getSelectedIndex());
        Integer index =  cbPedidoId.getSelectedIndex();
        if(index != -1)
        {
            this.pedido = listaPedidos.get(index);
            listaItens = pedido.getItens();
            modeloTabela.setLista(listaItens);
        }
        else
        {
            modeloTabela.limpaTabela();
        }

    }//GEN-LAST:event_cbPedidoIdItemStateChanged

    private void buVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buVoltarActionPerformed
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_buVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buBuscar;
    private javax.swing.JButton buVoltar;
    private javax.swing.JComboBox<String> cbPedidoId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JTextField tfCpf;
    // End of variables declaration//GEN-END:variables

}
