package org.ufpr.sistemapedidos.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.ufpr.sistemapedidos.Produto;
import org.ufpr.sistemapedidos.ProdutoDao;

public class ManterProduto extends javax.swing.JFrame {
    
    private modeloTabelaProdutos modeloTabela;
    private int linhaClicada = -1;

    public ManterProduto() {
        modeloTabela = new modeloTabelaProdutos();
        initComponents();
        this.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        tf_Busca = new javax.swing.JTextField();
        bu_Pesquisar = new javax.swing.JButton();
        bu_Salvar = new javax.swing.JButton();
        bu_Novo = new javax.swing.JButton();
        bu_Excluir = new javax.swing.JButton();
        tf_Descricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabelaProdutos.setModel(modeloTabela);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        bu_Pesquisar.setText("Pesquisar");
        bu_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_PesquisarActionPerformed(evt);
            }
        });

        bu_Salvar.setText("Salvar");
        bu_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_SalvarActionPerformed(evt);
            }
        });

        bu_Novo.setText("Novo");
        bu_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_NovoActionPerformed(evt);
            }
        });

        bu_Excluir.setText("Excluir");
        bu_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_ExcluirActionPerformed(evt);
            }
        });

        tf_Descricao.setText("Descrição");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_Descricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_Pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bu_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_Pesquisar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(tf_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bu_Novo)
                    .addComponent(bu_Salvar)
                    .addComponent(bu_Excluir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bu_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_PesquisarActionPerformed
        try {
            String termo = tf_Busca.getText();
            if(termo.equals("")){
                this.atualizaTabela();
            }
            else{
                ProdutoDao dao = new ProdutoDao();
                List<Produto> lista = dao.buscarProdutos(termo);
                modeloTabela.setLista(lista);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bu_PesquisarActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        linhaClicada = tabelaProdutos.rowAtPoint(evt.getPoint());
        Produto prod = modeloTabela.getProduto(linhaClicada);
        tf_Descricao.setText(prod.getDescricao());
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void bu_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_NovoActionPerformed
        if(tf_Descricao.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "Insira uma descrição", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            ProdutoDao dao = new ProdutoDao();
            String desc = tf_Descricao.getText();
            Produto prod = new Produto(desc);
            try {
                dao.incluirProduto(prod);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            this.atualizaTabela();
        }
    }//GEN-LAST:event_bu_NovoActionPerformed

    private void bu_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_SalvarActionPerformed
        if(linhaClicada==-1){
            JOptionPane.showMessageDialog(new JFrame(), "Selecione um produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        if(tf_Descricao.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "Insira uma descrição", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            ProdutoDao dao = new ProdutoDao();
            linhaClicada = tabelaProdutos.getSelectedRow();
            Produto prod = modeloTabela.getProduto(linhaClicada);
            Integer id = prod.getId();
        
            try {
                dao.alterarDescricao(id, tf_Descricao.getText());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            this.atualizaTabela();
        }
    }//GEN-LAST:event_bu_SalvarActionPerformed

    private void bu_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_ExcluirActionPerformed
        
        if(linhaClicada==-1)
        {
            JOptionPane.showMessageDialog(new JFrame(), "Selecione um produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                ProdutoDao dao = new ProdutoDao();
                linhaClicada = tabelaProdutos.getSelectedRow();
                Produto prod = modeloTabela.getProduto(linhaClicada);
                dao.removerProduto(prod.getId());
            } catch (SQLException ex) {
                Logger.getLogger(ManterProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.atualizaTabela();
        }
    }//GEN-LAST:event_bu_ExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterProduto().setVisible(true);
                
            }
        });
    }

    private void atualizaTabela() {
        try {
            ProdutoDao dao = new ProdutoDao();
            List<Produto> lista = dao.listarProdutos();
            linhaClicada = -1;
            modeloTabela.setLista(lista);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro ao atualizar tabela.", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_Excluir;
    private javax.swing.JButton bu_Novo;
    private javax.swing.JButton bu_Pesquisar;
    private javax.swing.JButton bu_Salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField tf_Busca;
    private javax.swing.JTextField tf_Descricao;
    // End of variables declaration//GEN-END:variables
}
