package org.ufpr.sistemapedidos.view;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.ufpr.sistemapedidos.Cliente;
import org.ufpr.sistemapedidos.ClienteDao;
import org.ufpr.sistemapedidos.Cpf;
import org.ufpr.sistemapedidos.PedidoDao;

public class ManterCliente extends javax.swing.JFrame {

    private modeloTabelaClientes modeloTabela;
    private int linhaClicada = -1;
    
    public ManterCliente() {
        modeloTabela = new modeloTabelaClientes();
        initComponents();
        this.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        tf_Nome = new javax.swing.JTextField();
        tf_Sobrenome = new javax.swing.JTextField();
        tf_Cpf = new javax.swing.JTextField();
        bu_Salvar = new javax.swing.JButton();
        bu_Novo = new javax.swing.JButton();
        bu_Buscar = new javax.swing.JButton();
        tf_Buscar = new javax.swing.JTextField();
        bu_GerarCpf = new javax.swing.JButton();
        bu_Excluir = new javax.swing.JButton();
        buVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TabelaClientes.setModel(modeloTabela);
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        tf_Nome.setText("Nome");

        tf_Sobrenome.setText("Sobrenome");

        tf_Cpf.setText("CPF");

        bu_Salvar.setText("Salvar");
        bu_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_SalvarActionPerformed(evt);
            }
        });

        bu_Novo.setText("Novo");
        bu_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_NovoActionPerformed(evt);
            }
        });

        bu_Buscar.setText("Buscar");
        bu_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_BuscarActionPerformed(evt);
            }
        });

        bu_GerarCpf.setText("Random CPF");
        bu_GerarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_GerarCpfActionPerformed(evt);
            }
        });

        bu_Excluir.setText("Excluir");
        bu_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_ExcluirActionPerformed(evt);
            }
        });

        buVoltar.setText("Voltar");
        buVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_Sobrenome)
                                    .addComponent(tf_Nome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(bu_GerarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bu_Novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bu_Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(bu_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bu_Buscar)
                    .addComponent(tf_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_Novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_Salvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bu_GerarCpf)
                    .addComponent(bu_Excluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        linhaClicada = TabelaClientes.rowAtPoint(evt.getPoint());
        Cliente cliente = modeloTabela.getCliente(linhaClicada);
        
        tf_Nome.setText(cliente.getNome());
        tf_Sobrenome.setText(cliente.getSobreNome());
        tf_Cpf.setText(cliente.getCpf());
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void bu_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_NovoActionPerformed
        try{
            ClienteDao dao = new ClienteDao();
            
            String nome = tf_Nome.getText();
            String sobrenome = tf_Sobrenome.getText();
            
            Cpf cpf = new Cpf(tf_Cpf.getText());
            
            if(cpf.isValid())
            {
                Cliente cliente = new Cliente(nome, sobrenome, cpf.toString());
                dao.incluirCliente(cliente);
                this.atualizaTabela();
            }
            else
            {
                JOptionPane.showMessageDialog(new JFrame(), "CPF inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bu_NovoActionPerformed

    private void bu_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_SalvarActionPerformed
        try {
            ClienteDao dao = new ClienteDao();
            
            linhaClicada = TabelaClientes.getSelectedRow();
            Cliente cliente = modeloTabela.getCliente(linhaClicada);
            Integer id = cliente.getId();
            
            Cpf cpf = new Cpf(tf_Cpf.getText());
            if(cpf.isValid())
            {
                dao.alterarCpf(id, cpf.toString());
                dao.alterarNome(id, tf_Nome.getText());
                dao.alterarSobrenome(id, tf_Sobrenome.getText());
            }
            else
            {
                JOptionPane.showMessageDialog(new JFrame(), "CPF inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        this.atualizaTabela();
    }//GEN-LAST:event_bu_SalvarActionPerformed

    private void bu_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_BuscarActionPerformed
        try {
            String termo = tf_Buscar.getText();
            if(termo.equals("")){
                this.atualizaTabela();
            }
            else {
                ClienteDao dao = new ClienteDao();
                List<Cliente> lista = dao.buscarClientes(termo);
                modeloTabela.setListaClientes(lista);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bu_BuscarActionPerformed

    private void bu_GerarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_GerarCpfActionPerformed
        Cpf cpf = new Cpf();
        tf_Cpf.setText(cpf.toString());
    }//GEN-LAST:event_bu_GerarCpfActionPerformed

    private void bu_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_ExcluirActionPerformed
        try {
            ClienteDao dao = new ClienteDao();
            PedidoDao pedidoDao = new PedidoDao();
            
            
            
            linhaClicada = TabelaClientes.getSelectedRow();
            Cliente cliente = modeloTabela.getCliente(linhaClicada);
            
            Integer num_pedidos = pedidoDao.listarPedidosDeCliente(cliente).size();
            if(num_pedidos==0)
            {
                dao.excluirCliente(cliente);
            }
            else
            {
                JOptionPane.showMessageDialog(new JFrame(), "Não é possível excluir cliente com pedidos", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        this.atualizaTabela();
    }//GEN-LAST:event_bu_ExcluirActionPerformed

    private void buVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buVoltarActionPerformed
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_buVoltarActionPerformed
    private void atualizaTabela()
    {
        try {
            ClienteDao dao = new ClienteDao();
            List<Cliente> lista = dao.listarClientes();
            linhaClicada = -1;
            modeloTabela.setListaClientes(lista);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new ManterCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JButton buVoltar;
    private javax.swing.JButton bu_Buscar;
    private javax.swing.JButton bu_Excluir;
    private javax.swing.JButton bu_GerarCpf;
    private javax.swing.JButton bu_Novo;
    private javax.swing.JButton bu_Salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf_Buscar;
    private javax.swing.JTextField tf_Cpf;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_Sobrenome;
    // End of variables declaration//GEN-END:variables
}
